name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kivy/buildozer-action@master
        with:
          buildozer_version: master
          python_version: 3.11
      - uses: actions/upload-artifact@v4
        with:
          name: DataRecycle-APK
          path: bin/*.apk
          
