name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Build
        uses: ArtemSerebryakov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.10
      - name: Save APK
        uses: actions/upload-artifact@v2
        with:
          name: DataRecyclePro-Package
          path: bin/*.apk
